on:
  # Trigger the workflow on push or
  # pull request, but only for the
  # master branch.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Weekly run to account for
  # changed dependencies.
  schedule:
    - cron: '17 04 * * 0'

name: CI
jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc:
          - '8.0'
          - '8.2'
          - '8.4'
          - '8.6'
          - '8.8'
          - '8.10'
          - '9.0'
          - 'latest'
        # Also build on macos. Windows seems flaky, with some
        # quickcheck failure appearing relatively consistent, but not
        # always.
        include:
          - os: macos-latest
            ghc: 'latest'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Configure
        run: cabal configure --enable-tests --enable-library-coverage

      - name: Build the code
        run: cabal build

      - name: Run tests
        run: cabal test

      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@v2
        with:
          target: stack:test
          excludes: Main,Paths_my_package

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          name: codecov-${{ matrix.os }}-${{ matrix.ghc }}
